version: '3'
services:
  # Node.js application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3307
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'abcd1234'
      MYSQL_DATABASE: 'shyftlabs'

  # MySQL service
  db:
    image: mysql:8.1.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'abcd1234'
      MYSQL_DATABASE: 'shyftlabs'
